simulated_data <-
  tibble(
    apartment_id = 1:1000,
    'age' = runif(n = 1000,
                          min = 0.5, 
                          max = 100),
    'SECURITY' = as.integer(runif(n = 1000,
                          min = 0, 
                          max = 5)),
    'ELEVATORS' = as.integer(runif(n = 1000,
                          min = 0, 
                          max = 5)),
    'INTERIOR_WALL_CEILING_FLOOR' = as.integer(runif(n = 1000,
                          min = 0, 
                          max = 5)),
    'GRAFFITI' = as.integer(runif(n = 1000,
                          min = 0, 
                          max = 5)),
    'EXTERIOR_CLADDING' = as.integer(runif(n = 1000,
                          min = 0, 
                          max = 5)),
    'WATER_PEN_EXT_BLDG_ELEMENTS' = as.integer(runif(n = 1000,
                          min = 0, 
                          max = 5)),
    'GARBAGE_CHUTE_ROOMS' = as.integer(runif(n = 1000,
                          min = 0, 
                          max = 5)),
    )

